name: Convert PNG to WebP

on:
  workflow_dispatch: # Agora aparece o botão de execução manual
  push:
    paths:
      - '**.png'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup tools
      run: sudo apt-get install -y webp pngquant
      
    - name: Convert files
      run: |
        find . -name '*.png' | while read png; do
          webp="${png%.*}.webp"
          mkdir -p "$(dirname "$webp")"
          cwebp -q 85 "$png" -o "$webp"
        done
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Convert PNG to WebP [skip ci]" || echo "No changes"
        git push
