name: Convert JPG to WebP

on:
  workflow_dispatch:  # Permite execução manual
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install WebP tools
      run: sudo apt-get install -y webp
      
    - name: Convert files
      run: |
        find . \( -iname "*.jpg" -o -iname "*.jpeg" \) | while read jpg; do
          webp="${jpg%.*}.webp"
          cwebp -q 85 "$jpg" -o "$webp"
          echo "Convertido: $jpg → $webp"
        done
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto: Convert JPG to WebP [skip ci]" || echo "Sem alterações"
        git push
